### ISSUE TITLE
Baseline PWA features

### ISSUE THREAD

**Issue by addyosmani** [vuejs/pwa#1]
Cross-posting from our original discussion at https://github.com/vuejs/vue-cli/issues/381. Will make a start on this shortly.

There are a few different options for what this could include:

> Web Application Manifest
> Default favicons (minimalist setup from realfavicongenerator.net)
> Service Worker precaching + runtime caching via sw-precache-webpack-plugin
> Application Shell architecture
> Code-splitting by default with vue-router
> If we wanted to go even more ambitious we could cover:
> 
> PRPL pattern support (using something like preload-webpack-plugin)
> Simple server-side rendering + pre-fetching
> CSS extraction for production
> Requirements
> 
> Aim to score as close to 100/100 on Lighthouse
> Must be straight-forward to use. If we make it inherently complex, it will lose value to end users.
> Prior-art - PWA templates and boilerplates 🎨
> 
> https://github.com/Narkoleptika/webpack-everything
> https://github.com/electricjesus/vue-pwa-template
> https://github.com/BosNaufal/vue-simple-pwa
> Vue.js PWAs (open-source) 👐
> 
> https://github.com/vuejs/vue-hackernews-2.0
> https://github.com/GoogleChrome/jscost.org (not yet fully released)
> https://github.com/mrgodhani/feedbox
> https://github.com/bstavroulakis/vue-wordpress-pwa
> Other references 📚
> 
> PRPL pattern with Webpack and React
> Initially, I would love to get a feel for what would considered palatable for an MVP. There's technically nothing stopping us baking in everything in the above list, but let's talk and figure out a path forward 🚀

**Comment by addyosmani** [comment]
We're now up to this point with Lighthouse:

![image](https://cloud.githubusercontent.com/assets/110953/24641629/1710c31c-18b6-11e7-84b0-5eb9f9ea8d1a.png)

Real score is probably +10-20 when serving over HTTPS.

Major parts left:

- Contains some content when JavaScript is not available - need to decide whether to inline "shell CSS" or critical CSS or SSR
- Background and foreground colors have a sufficient contrast ratio 
- Every image element has an alt attribute (logo)

**Comment by addyosmani** [comment]
And bumped up with some fallback content:

![image](https://cloud.githubusercontent.com/assets/110953/24641930/5f8f9896-18b8-11e7-9ff4-d0f3222536ce.png)

For now, I'll probably encourage the user to decide if they want to specify fallback content or go for Vue's SSR support themselves.

Last two items there will be looked at next.

**Comment by Naramsim** [comment]
Could be really nice to have an option to opt-in for AMP. https://developers.google.com/web/shows/google-io/2016/amp-progressive-web-apps-start-fast-stay-engaged-google-io-2016

**Comment by rwatts3** [comment]
Nice work ! This will truly be a historic moment.

**Comment by zyzski** [comment]
After doing some work on a vue PWA, the biggest challenge i've faced (besides some crazy webpack configging) is handling the app shell. It's simple enough to inline critical CSS and style a basic app shell in the index.html template, but there's no way to avoid the long frame/FPS hit when vue writes the entire app to the dom. The current solution right now seems to be SSR.

I'm curious if anyone has been able to solve this on the client side, but might be better to discuss in a different thread?

@addyosmani I would also look in to adding evan's code from vue-hackernews2 to generate preload/prefetch tags from chunks:
https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/index.template.html#L11

**Comment by addyosmani** [comment]
@zyzski I'd definitely be open to discussing those challenges in a separate thread. The interesting decision for us to make with Vue's PWA story is balancing how much we bake into the template vs deferring out to docs (and I do think we should have Vue docs that talk about some of these trade-offs you do run into production). Want to file an issue?

On preloading: I initially thought about using https://github.com/googlechrome/preload-webpack-plugin for this purpose, but I'll definitely take a look at Evan's code for this. If we're fine with prescribing a simpler pattern I'm also down for that.

**Comment by zyzski** [comment]
@addyosmani makes sense. i'm not really comfortable creating an issue about it just yet, because I am new-ish to vue and detailed performance testing. to be fair, the framework is already hitting goal perf metrics, I was just wondering about pushing it a bit further.

on preloading: I didn't know that plugin existed and was using vue-hn2 as my reference while building so I just used his method, looks like they do the same thing

**Comment by addyosmani** [comment]
Here's where we stand now with performance on an emerging market network + real phone: https://www.webpagetest.org/lighthouse.php?test=170407_FD_5Q4F&run=3 (original run is https://www.webpagetest.org/result/170407_FD_5Q4F/).

Time to interactive is under 5s (4.4s), but is still a little too close to give folks some good legroom.

Scaffold uses ~45KB. App's about 7.7KB and vendor is 35KB.

https://test-vue-pwa.firebaseapp.com/

With CPU throttling on, we're seeing 1.3-1.4s spent in JavaScript startup:

![image](https://cloud.githubusercontent.com/assets/110953/24821040/2c1a16b2-1ba1-11e7-82ec-5cf372f6aa22.png)

Going to see how much of that we can trim back.

**Comment by yyx990803** [comment]
FYI if we use the [runtime only build](https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only) we can shave off another ~7kb

**Comment by addyosmani** [comment]
Oh wow. I had no idea runtime only builds were a thing. I'll give that a try too.

**Comment by addyosmani** [comment]
Putting together the final MVP list of things to tackle.

I've got #6 (runtime build) and was then going to look at whether there's more work to be done for the Application Shell architecture. 

@yyx990803 Do you have any opinions on default UI? Right now I'm using the same type of HTML output the Webpack template uses (Vue logo with text). Could implement a simple application header nav to highlight the "shell" concept. If we do this, might be worth just adding in via HTML + CSS rather than pulling in a whole Vue CSS library.

**Comment by yyx990803** [comment]
@addyosmani yeah, I think a simple Material-style app shell with Vue theme colors could be nice :) And just some raw HTML + CSS should suffice.

**Comment by addyosmani** [comment]
Closing this one up as we've hit baseline.
